### ISSUE TITLE
Query seems to be aimed at finding users in your e-wallet application who are inactive as of a specific date (7/3/24). 

### ISSUE THREAD

**Issue by nazrinrazak** [baratiga/sample-query#1]
Few improvements and potential issues in the provided code

**Comment by baratiga** [comment]
noted, i noticed that i made a typo in calling the table in the nested query. Thanks!

**Comment by baratiga** [comment]
> Few improvements and potential issues in the provided code

Hi Nazrin, FYA I have already corrected the error ya. Thanks!

**Comment by nazrinrazak** [comment]
Great! Uno problemo.
